name: build-and-push

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend
          push: true
          tags: user/incasi-backend:latest
      -
        name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/incassi
          push: true
          tags: user/incassi-frontend:latest

